Traceback (most recent call last):
  File "../../kolumny", line xxx, in <module>
    plik = file(e)
IOError: [Errno 2] No such file or directory: '1'
